# Site settings
title: JUJU - Art for Everyone
email: hello@sharethejuju.com
description: We need a description.... coming from GUY
baseurl: ""
url: "http://sharethejuju.com"

# Build settings
markdown: kramdown
exclude: [Gemfile*, scss, *.json, _config.yml]