# Site settings
title: JUJU - Art for Everyone
email: hello@sharethejuju.com
description: Mix art and Send Good JUJU - iPhone App
baseurl: ""
url: "http://sharethejuju.com"

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, scss, bower.json, package.json]
